# Generated by Django 6.0.6 on 2026-06-25 09:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.PositiveIntegerField(default=1, help_text='Current hunter rank / level.')),
                ('current_xp', models.PositiveIntegerField(default=0, help_text='XP earned toward the next level.')),
                ('total_xp', models.PositiveIntegerField(default=0, help_text='Lifetime XP accumulated.')),
                ('streak_days', models.PositiveIntegerField(default=0, help_text='Consecutive days with a completed workout.')),
                ('avatar', models.ImageField(blank=True, help_text='Profile image for the hunter avatar.', null=True, upload_to='avatars/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User profile',
                'verbose_name_plural': 'User profiles',
                'ordering': ['-updated_at'],
            },
        ),
    ]
