# Generated by Django 6.0.6 on 2026-06-25 09:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('exercises', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Workout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('notes', models.TextField(blank=True)),
                ('duration_minutes', models.PositiveIntegerField(blank=True, help_text='Total session length in minutes.', null=True)),
                ('calories_burned', models.PositiveIntegerField(blank=True, help_text='Estimated calories burned for the session.', null=True)),
                ('completed', models.BooleanField(default=False, help_text='Whether the workout has been finished.')),
                ('completed_at', models.DateTimeField(blank=True, help_text='Timestamp when the workout was marked complete.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workouts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Workout',
                'verbose_name_plural': 'Workouts',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WorkoutExercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sets', models.PositiveIntegerField(default=1, help_text='Number of sets performed.')),
                ('reps', models.PositiveIntegerField(default=10, help_text='Repetitions per set.')),
                ('weight', models.DecimalField(decimal_places=2, default=0, help_text="Weight used per set (user's preferred unit).", max_digits=6)),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='workout_entries', to='exercises.exercise')),
                ('workout', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workout_exercises', to='workouts.workout')),
            ],
            options={
                'verbose_name': 'Workout exercise',
                'verbose_name_plural': 'Workout exercises',
                'ordering': ['id'],
            },
        ),
    ]
