# Generated by Django 6.0.6 on 2026-06-29 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0001_initial'),
        ('workouts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='workoutexercise',
            options={'ordering': ['order'], 'verbose_name': 'Workout exercise', 'verbose_name_plural': 'Workout exercises'},
        ),
        migrations.AddField(
            model_name='workoutexercise',
            name='order',
            field=models.PositiveIntegerField(default=1, help_text='Position of the exercise within the workout.'),
        ),
        migrations.AddField(
            model_name='workoutexercise',
            name='rest_seconds',
            field=models.PositiveIntegerField(default=60, help_text='Rest time between sets in seconds.'),
        ),
        migrations.AddConstraint(
            model_name='workoutexercise',
            constraint=models.UniqueConstraint(fields=('workout', 'order'), name='unique_workout_exercise_order'),
        ),
    ]
