# Generated by Django 6.0.6 on 2026-07-01 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0002_alter_workoutexercise_options_workoutexercise_order_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='workout',
            name='muscle_group',
            field=models.CharField(choices=[('Chest', 'Chest'), ('Back', 'Back'), ('Legs', 'Legs'), ('Shoulders', 'Shoulders'), ('Arms', 'Arms'), ('Core', 'Core'), ('Full Body', 'Full Body')], default='Full Body', max_length=50),
        ),
    ]
