# Generated by Django 6.0.6 on 2026-06-25 09:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('xp_reward', models.PositiveIntegerField(help_text='XP awarded when the quest is claimed.')),
                ('target_value', models.PositiveIntegerField(default=1, help_text='Goal count, e.g. complete 1 workout.')),
                ('active', models.BooleanField(default=True, help_text='Whether this quest can be assigned to users.')),
            ],
            options={
                'verbose_name': 'Quest template',
                'verbose_name_plural': 'Quest templates',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='XPTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(help_text='XP change. Positive for gains, negative for penalties.')),
                ('reason', models.CharField(help_text='Why XP changed, e.g. workout_complete, quest_claimed.', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='xp_transactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'XP transaction',
                'verbose_name_plural': 'XP transactions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='QuestProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('progress', models.PositiveIntegerField(default=0, help_text='Current progress toward target_value.')),
                ('completed', models.BooleanField(default=False, help_text='Whether the quest target has been met.')),
                ('claimed', models.BooleanField(default=False, help_text='Whether the user collected the XP reward.')),
                ('completed_at', models.DateTimeField(blank=True, help_text='When the quest was marked complete.', null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quest_progress', to=settings.AUTH_USER_MODEL)),
                ('quest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress_records', to='gamification.questtemplate')),
            ],
            options={
                'verbose_name': 'Quest progress',
                'verbose_name_plural': 'Quest progress records',
                'ordering': ['-completed_at', '-id'],
                'unique_together': {('user', 'quest')},
            },
        ),
    ]
