# Generated by Django 6.0.6 on 2026-06-25 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
                ('muscle_group', models.CharField(help_text='Primary muscle group, e.g. chest, legs, back.', max_length=50)),
                ('equipment', models.CharField(blank=True, help_text='Equipment needed, e.g. barbell, dumbbell, bodyweight.', max_length=50)),
                ('difficulty', models.CharField(blank=True, help_text='beginner, intermediate, or advanced.', max_length=20)),
                ('description', models.TextField(blank=True, help_text='Short instructions or notes about the exercise.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Exercise',
                'verbose_name_plural': 'Exercises',
                'ordering': ['muscle_group', 'name'],
            },
        ),
    ]
